--- #YAML:1.0
name: DateTime-Format-Mail
version: 0.2901
license: perl
distribution_type: module
requires:
  DateTime: 0.1705
  Params::Validate: 0.67
  Test::More: 0.47
recommends: {}
build_requires: {}
conflicts: {}
provides:
  DateTime::Format::Mail:
    file: lib/DateTime/Format/Mail.pm
    version: 0.2901
generated_by: Module::Build version 0.21
