--- #YAML:1.0
distribution_type: module
name: DateTime-Format-Mail
date: 1 Aug 2003
author: SPOON
version: 0.27
license: perl

conflicts: {}

build_requires:
  Test::More: 0.47
recommends:
  File::Find::Rule: 0.11
  Test::Pod: 0.95
  Test::Signature: 1.04
requires:
  DateTime: 0.1501
  Params::Validate: 0.64

private:
  directory:
    - t

provides:
  DateTime::Format::Mail:
    file: lib/DateTime/Format/Mail.pm
    version: 0.27

dynamic_config: 0
generated_by: docmaker version 0.91
