--- #YAML:1.0
# http://module-build.sourceforge.net/META-spec.html
distribution_type: module
name: DateTime-Format-Mail
date: 21 Oct 2003
author: SPOON
version: 0.28
license: perl

conflicts: {}

build_requires:
  Test::More: 0.47
recommends:
  File::Find::Rule: 0.24
  Test::Pod: 0.95
  Test::Signature: 1.05
requires:
  DateTime: 0.1705
  Params::Validate: 0.67

private:
  directory:
    - t

provides:
  DateTime::Format::Mail:
    file: lib/DateTime/Format/Mail.pm
    version: 0.28

dynamic_config: 0
generated_by: docmaker version 1.01
