#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime-Format-Mail
version:      0.24
version_from: lib/DateTime/Format/Mail.pm
installdirs:  site
requires:
    Test::More:                    0.47
    DateTime:                      0.09
    Params::Validate:              0.58

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_02
