--- #YAML:1.0
distribution_type: module
name: DateTime-Format-Mail
version: 0.26
license: perl

conflicts: {}

build_requires:
  Test::More: 0.47
recommends:
  File::Find::Rule: 0.10
  Test::Pod: 0.95
  Test::Signature: 1.04
requires:
  DateTime: 0.14
  Params::Validate: 0.64

private:
  directory:
    - t

provides:
  DateTime::Format::Mail:
    file: lib/DateTime/Format/Mail.pm
    version: 0.26

generated_by: docmaker version 0.89
